import React, { useEffect } from "react";

const PrivacyPolicy = () => {
  const header = {
    marginBottom: "15px",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: "35px",
  };

  const tableStyle = {
    width: "100%",
    borderCollapse: "collapse",
    marginBottom: "30px",
  };

  const thTdStyle = {
    border: "5px solid #ddd",
    padding: "8px",
    textAlign: "left",
  };

  const sectionStyle = {
    marginBottom: "20px",
  };

  const sectionheader = {
    fontSize: "30px",
    marginBottom: "10px",
    fontWeight: "bold",
  };

  const sectionsubheader = {
    fontSize: "20px",
    marginBottom: "10px",
    fontWeight: "bold",
  };

  const listStyle = {
    paddingLeft: "20px",
    fontSize: "18px",
  };

  const paragraph = {
    fontSize: "20px",
  };

  useEffect(() => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  }, []);

  return (
    <div >
      <h1 style={header}>Privacy Policy</h1>
      <table style={tableStyle}>
        <tbody>
          <tr>
            <th style={thTdStyle}>Last Updated</th>
            <td style={thTdStyle}>Jan 16, 2020</td>
          </tr>
          <tr>
            <th style={thTdStyle}>Company</th>
            <td style={thTdStyle}>
              Himalayan Circuit, a registered Company of Himalayan Circuit Team
              Pvt Ltd. Before 2019, this company was known as GAP Adventure
              Trekking & Expedition Pvt Ltd.
            </td>
          </tr>
          <tr>
            <th style={thTdStyle}>GDPR</th>
            <td style={thTdStyle}>
              Means the General Data Protection Regulation.
            </td>
          </tr>
          <tr>
            <th style={thTdStyle}>Responsible Person</th>
            <td style={thTdStyle}>Prakash BC</td>
          </tr>
          <tr>
            <th style={thTdStyle}>Register of Systems</th>
            <td style={thTdStyle}>
              A register of all systems or contexts in which personal data is
              processed by the Company.
            </td>
          </tr>
        </tbody>
      </table>
      <section style={sectionStyle}>
        <h2 style={sectionheader}>Introduction</h2>
        <p style={paragraph}>
          Himalayan Circuit (“us”, “we”, or “our”) operates the
          HimalayanCircuit.Com website (the “Company”). This page informs you of
          our policies regarding the collection, use, and disclosure of personal
          data when you use our Company and the choices you have associated with
          that data.
        </p>
        <p style={paragraph}>
          By using the Service, you agree to the collection and use of
          information in accordance with this policy.
        </p>
      </section>
      <section style={sectionStyle}>
        <h2 style={sectionheader}>Definitions</h2>
        <ul style={listStyle}>
          <li>
            <strong>Service:</strong> The website operated by Himalayan Circuit.
          </li>
          <li>
            <strong>Personal Data:</strong> Information about a living
            individual who can be identified from that data.
          </li>
          <li>
            <strong>Usage Data:</strong> Data collected automatically, either
            generated by the use of the Service or from the Service
            infrastructure itself.
          </li>

          <li>
            <strong>Cookies:</strong> Cookies are small pieces of data stored on
            your device (computer or mobile device).
          </li>
          <li>
            <strong>Data Controller:</strong> Data Controller means the natural
            or legal person who (either alone or jointly or in common with other
            persons) determines the purposes for which and the manner in which
            any personal information are, or are to be, processed. For the
            purpose of this Privacy Policy, we are a Data Controller of your
            Personal Data.
          </li>
          <li>
            <strong>Data Processors (or Company Providers):</strong> Data
            Processor (or Company Provider) means any natural or legal person
            who processes the data on behalf of the Data Controller. We may use
            the services of various Company Providers in order to process your
            data more effectively.
          </li>
          <li>
            <strong>Data Subject (or User):</strong> Data Subject is any living
            individual who is using our Company and is the subject of Personal
            Data.
          </li>
        </ul>
      </section>
      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>Information Collection and Use</h2>
        <p style={paragraph}>
          We collect several different types of information for various purposes
          to provide Services and improve our Company to you.
        </p>
        <p style={paragraph}>
          Our customer data is kept according to the legal requirements
          applicable to registered migration agents. A registered Tour Operator
          must keep the file records of a client for a period of 5 years after
          the date of the last action on the file for the client.
        </p>
      </section>
      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>Types of Data Collected</h2>
        <h3 style={sectionsubheader}>Personal Data</h3>
        <p style={paragraph}>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally identifiable information
          may include, but is not limited to:
        </p>
        <ul style={listStyle}>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Passport data</li>
          <li>Medical History</li>
          <li>All data you enter into our questionnaires</li>
        </ul>
        <p style={paragraph}>
          We may use your Personal Data to conduct our services, contact you
          with newsletters, marketing or promotional materials, and other
          information that may be of interest to you. You may opt out of
          receiving any, or all, of these communications from us by following
          the unsubscribe link or instructions provided in any email we send or
          by contacting us.
        </p>
      </section>
      <section style={sectionStyle}>
        <h3 style={sectionsubheader}>Usage Data</h3>
        <p style={paragraph}>
          We may also collect information how the Company is accessed and used
          (“Usage Data”). This Usage Data may include information such as your
          computer’s Internet Protocol address (e.g., IP address), browser type,
          browser version, the pages of our Company that you visit, the time and
          date of your visit, the time spent on those pages, unique device
          identifiers and other diagnostic data.
        </p>
      </section>
      <section style={sectionStyle}>
        <h3 style={sectionsubheader}>Location Data</h3>
        <p style={paragraph}>
          We may use and store information about your location if you give us
          permission to do so (Location Data). We use this data to provide
          features of our Service, to improve and customize our Service.
        </p>
        <p style={paragraph}>
          You can enable or disable location services when you use our Company
          at any time, through your device settings.
        </p>
      </section>
      <section style={sectionStyle}>
        <h3 style={sectionsubheader}>Tracking & Cookies Data</h3>
        <p style={paragraph}>
          We use cookies and similar tracking technologies to track the activity
          on our Company and hold certain information.
        </p>
        <p style={paragraph}>
          Cookies are files with small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Tracking technologies also used are
          beacons, tags, and scripts to collect and track information and to
          improve and analyze our Service.
        </p>
        <p style={paragraph}>
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>
        <p style={paragraph}>Examples of Cookies we use:</p>
        <ul style={listStyle}>
          <li>
            Session Cookies. We use Session Cookies to operate our Service.
          </li>
          <li>
            Preference Cookies. We use Preference Cookies to remember your
            preferences and various settings.
          </li>
          <li>
            Security Cookies. We use Security Cookies for security purposes.
          </li>
        </ul>
      </section>
      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>Use of Data</h2>
        <ul style={listStyle}>
          <li>To provide tour and trekking Service</li>
          <li>To provide and maintain our Service</li>
          <li>To notify you about changes to our Service</li>
          <li>
            To allow you to participate in interactive features of our Company
            when you choose to do so
          </li>
          <li>To provide customer support</li>
          <li>
            To gather analysis or valuable information so that we can improve
            our Service
          </li>
          <li>To monitor the usage of our Service</li>
          <li>To detect, prevent and address technical issues</li>
          <li>
            To provide you with news, special offers and general information
            about other goods, services, and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information
          </li>
        </ul>
      </section>

      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>
          Legal Basis for Processing Personal Data Under General Data Protection
          Regulation (GDPR)
        </h2>
        <p style={paragraph}>
          If you are from the European Economic Area (EEA), Himalayan Circuit
          Team Pvt Ltd legal basis for collecting and using the personal
          information described in this Privacy Policy depends on the Personal
          Data we collect and the specific context in which we collect it.
        </p>
        <ul style={listStyle}>
          <li>We need to perform a contract with you</li>
          <li>You have given us permission to do so</li>
          <li>
            The processing is in our legitimate interests and it’s not
            overridden by your rights
          </li>
          <li>For payment processing purposes</li>
          <li>To comply with the law</li>
        </ul>
      </section>

      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>Retention of Data</h2>
        <p style={paragraph}>
          Himalayan Circuit Team Pvt Ltd will retain your Personal Data only for
          as long as is necessary for the purposes set out in this Privacy
          Policy. We will retain and use your Personal Data to the extent
          necessary to comply with our legal obligations (for example, if we are
          required to retain your data to comply with applicable laws), resolve
          disputes, and enforce our legal agreements and policies.
        </p>
        <p style={paragraph}>
          Himalayan Circuit Team Pvt Ltd will also retain Usage Data for
          internal analysis purposes. Usage Data is generally retained for a
          shorter period of time, except when this data is used to strengthen
          the security or to improve the functionality of our Service, or we are
          legally obligated to retain this data for longer time periods.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>Transfer of Data</h2>
        <p style={paragraph}>
          Your information, including Personal Data, may be transferred to
          Australia and maintained on Australian computers located outside of
          your state, province, country or other governmental jurisdiction where
          the data protection laws may differ than those from your jurisdiction.
        </p>
        <p style={paragraph}>
          If you are located outside Australia and choose to provide information
          to us, please note that we transfer the data, including Personal Data,
          to Australia and process it there.
        </p>
        <p style={paragraph}>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p style={paragraph}>
          Himalayan Circuit Team Pvt Ltd will take all steps reasonably
          necessary to ensure that your data is treated securely and in
          accordance with this Privacy Policy and no transfer of your Personal
          Data will take place to an organization or a country unless there are
          adequate controls in place including the security of your data and
          other personal information.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>Disclosure of Data</h2>
        <h3 style={sectionsubheader}>Visa Application</h3>
        <p style={paragraph}>
          For conducting our visa services for tour, we have to submit personal
          information provided by you through our online / email / phone call to
          the Government of Nepal, or any other country where you prefer to
          travel with us, which processes the visa applications, to the
          necessary extent.
        </p>

        <h3 style={sectionsubheader}>Disclosure for Law Enforcement</h3>
        <p style={paragraph}>
          Under certain circumstances, Himalayan Circuit Team Pvt Ltd may be
          required to disclose your Personal Data if required to do so by law or
          in response to valid requests by public authorities (e.g., a court or
          a government agency).
        </p>

        <h3 style={sectionsubheader}>Legal Requirements</h3>
        <p style={paragraph}>
          Himalayan Circuit Team Pvt Ltd may disclose your Personal Data in the
          good faith belief that such action is necessary to:
        </p>
        <ul style={listStyle}>
          <li>To comply with a legal obligation</li>
          <li>
            To protect and defend the rights or property of Himalayan Circuit
            Team Pvt Ltd
          </li>
          <li>
            To prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>
            To protect the personal safety of users of the Company or the public
          </li>
          <li>To protect against legal liability</li>
        </ul>
      </section>

      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>Security of Data</h2>
        <p style={paragraph}>
          The security of your data is important to us, but remember that no
          method of transmission over the Internet, or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>
          Your Data Protection Rights Under General Data Protection Regulation
          (GDPR)
        </h2>
        <p style={paragraph}>
          If you are a resident of the European Economic Area (EEA), you have
          certain data protection rights. Himalayan Circuit Team Pvt Ltd aims to
          take reasonable steps to allow you to correct, amend, delete, or limit
          the use of your Personal Data.
        </p>
        <ul style={listStyle}>
          <li>
            The right to access, update or delete the information we have on
            you.
          </li>
          <li>The right of rectification.</li>
          <li>The right to object to our processing of your Personal Data.</li>
          <li>The right of restriction.</li>
          <li>The right to data portability.</li>
          <li>The right to withdraw consent.</li>
        </ul>
        <p style={paragraph}>
          You have the right to complain to a Data Protection Authority about
          our collection and use of your Personal Data.
        </p>
      </section>

      <section style={sectionStyle}>
        <h2 style={sectionsubheader}>Company Providers</h2>
        <p style={paragraph}>
          We may employ third-party companies and individuals to facilitate our
          Company (“Company Providers”), to provide the Company on our behalf,
          to perform Service-related services or to assist us in analyzing how
          our Company is used.
        </p>
        <p style={paragraph}>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>
      </section>
      <section style={sectionStyle}>
  <h2 style={sectionsubheader}>Analytics</h2>
  <p style={paragraph}>
    We may use third-party Company Providers to monitor and analyze the use of our Service.
  </p>
  <h3 style={sectionsubheader}>Google Analytics</h3>
  <p style={paragraph}>
    Google Analytics is a web analytics Company offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network. You can opt-out of having made your activity on the Company available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.
  </p>
  <p style={paragraph}>
    For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en">Google Privacy & Terms</a>
  </p>
</section>

<section style={sectionStyle}>
  <h2 style={sectionsubheader}>Behavioral Remarketing</h2>
  <p style={paragraph}>
    Himalayan Circuit Team Pvt Ltd uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
  </p>
  <h3 style={sectionsubheader}>Google AdWords</h3>
  <p style={paragraph}>
    Google AdWords remarketing Company is provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads">Google Ads Settings</a>
  </p>
  <h3 style={sectionsubheader}>Twitter</h3>
  <p style={paragraph}>
    You can opt-out from Twitter’s interest-based ads by following their instructions: <a href="https://support.twitter.com/articles/20170405">Twitter Opt-Out</a>
  </p>
  <h3 style={sectionsubheader}>Facebook</h3>
  <p style={paragraph}>
    To opt-out from Facebook’s interest-based ads follow these instructions from Facebook: <a href="https://www.facebook.com/help/568137493302217">Facebook Opt-Out</a>
  </p>
  <h3 style={sectionsubheader}>AdRoll</h3>
  <p style={paragraph}>
    You can opt-out of AdRoll remarketing by visiting this <a href="http://info.evidon.com/pub_info/573?v=1&nt=1&nw=false">AdRoll Advertising Preferences</a> web page.
  </p>
</section>

<section style={sectionStyle}>
  <h2 style={sectionsubheader}>Payments</h2>
  <p style={paragraph}>
    We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).
  </p>
  <p style={paragraph}>
    We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express, and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
  </p>
  <h3 style={sectionsubheader}>Payment Processors</h3>
  <ul style={listStyle}>
    <li><a href="https://stripe.com/us/privacy">Stripe Privacy Policy</a></li>
    <li><a href="https://www.paypal.com/webapps/mpp/ua/privacy-full">PayPal Privacy Policy</a></li>
    <li><a href="https://www.mastercard.us/en-us/about-mastercard/what-we-do/privacy.html">MasterCard Privacy Policy</a></li>
  </ul>
</section>

<section style={sectionStyle}>
  <h2 style={sectionsubheader}>Links to Other Sites</h2>
  <p style={paragraph}>
    Our Company may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.
  </p>
  <p style={paragraph}>
    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
  </p>
</section>

<section style={sectionStyle}>
  <h2 style={sectionsubheader}>Children’s Privacy</h2>
  <p style={paragraph}>
    Our Company does not address anyone under the age of 18 (“Children”).
  </p>
  <p style={paragraph}>
    We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
  </p>
</section>

<section style={sectionStyle}>
  <h2 style={sectionsubheader}>Changes to This Privacy Policy</h2>
  <p style={paragraph}>
    We may update our Privacy Policy from time to time. We will notify by websites of any changes by posting the new Privacy Policy on this page.
  </p>
  <p style={paragraph}>
    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
  </p>
</section>

<section style={sectionStyle}>
  <h2 style={sectionsubheader}>Contact Us</h2>
  <p style={paragraph}>
    If you have any questions about this Privacy Policy, please contact us:
  </p>
  <ul style={listStyle}>
    <li>By e-mail: <a href="mailto:connect@himalayancircuit.com">connect@himalayancircuit.com</a></li>
    <li>By mail: Himalayan Circuit Team Pvt Ltd (HimalayanCircuit.Com), Meiphi 16, Nayabazar, Kathmandu, Nepal</li>
  </ul>
</section>

    </div>
  );
};

export default PrivacyPolicy;
